version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
